[package]
name = "rreng"
version = "0.1.0"
edition = "2021"

[dependencies]
noise = "0.9.0"
rand = "0.8.5"
serde = "1.0.198"
serde_json = "1.0.116"
tiff = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.13.2"
default-features = false
features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_render",
    "bevy_pbr",
    "webgl2"
]
