[package]
name = "rreng"
version = "0.2.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
noise = "0.9"
ndarray = "0.16"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tiff = "0.9"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.14"
default-features = false
features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_gltf",
    "bevy_state",
    "bevy_render",
    "bevy_pbr",
    "bevy_gizmos",
    "bevy_ui",
    "png",
    "webgl2"
]

[dependencies.bevy-inspector-egui]
version = "0.25"
default-features = false
features = [
    "bevy_render"
]

[dependencies.bevy_mod_raycast]
version = "0.18"
default-features = false

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
strip = true
