[package]
name = "rreng"
version = "0.5.0"
edition = "2021"
rust-version = "1.75"
default-run = "rreng"

[dependencies]
earcutr = "0.4"
geotiff = { git = "https://github.com/georust/geotiff", rev = "4df760b" }
glob = "0.3"
noise = "0.9"
ndarray = "0.16"
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tiff = "0.9"
toml = "0.8"
tracing-subscriber = "0.3"

[dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_asset",
    "bevy_gltf",
    "bevy_state",
    "bevy_render",
    "bevy_mesh_picking_backend",
    "bevy_ui_picking_backend",
    "bevy_picking",
    "bevy_pbr",
    "bevy_gizmos",
    "bevy_ui",
    "bevy_window",
    "animation",
    "multi_threaded",
    "png",
    "webgl2"
]

[dependencies.bevy-inspector-egui]
version = "0.28"
default-features = false
features = [
    "bevy_render"
]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
strip = true

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
